name: Nix flake check
on: pull_request

jobs:
  get-matrix:
    runs-on: [self-hosted, nix]
    outputs:
      check-matrix: ${{ steps.set-check-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-check-matrix
        run: echo "matrix=$(nix eval --json .#check-matrix.x86_64-linux)" >> $GITHUB_OUTPUT

  check:
    needs: get-matrix
    name: check ${{ matrix.check }}
    runs-on: [self-hosted, nix]
    strategy:
      fail-fast: false
      # this matrix consists of the names of all checks defined in flake.nix
      matrix: ${{fromJson(needs.get-matrix.outputs.check-matrix)}}
    steps:
      - uses: actions/checkout@v4

      - name: check
        run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}
